#!/bin/bash
soc=`sed '/#/d' INCAR|grep 'LSORBIT'|awk '{print $1}'`
if [ $1 ]
then
  vb=$1
else
  ne=`sed -n '6p' EIGENVAL|awk '{print $1}'`
  if [ $soc ]
  then
    vb=$ne
  else
    vb=$[(ne+1)/2]
  fi
fi
echo "$vb"|effmass.x > /dev/null
echo -e "VBM: \c"
sed -n '5,$p' mass.dat|sed '/+/d'|sort -g -k 3|tail -1|awk '{printf("%10.2E\n",$4)}'
echo -e "CBM: \c"
sed -n '5,$p' mass.dat|sed '/+/d'|sort -g -k 5|head -1|awk '{printf("%10.2E\n",$6)}'
